import pandas as pd
import joblib
import numpy as np
import os

# --- CONFIGURATION ---
# Ensure this path matches the file generated by the Notebook
MODEL_PATH = 'saved_models/xgb_weather_models.joblib'
DATA_PATH = 'HCM.csv'

def get_latest_data_from_csv():
    """
    Simulate real-time data fetching by reading the last row of the historical CSV.
    """
    if not os.path.exists(DATA_PATH):
        print(f"Error: Data file not found at {DATA_PATH}")
        return None
        
    df = pd.read_csv(DATA_PATH)
    df.columns = df.columns.str.strip().str.lower()
    
    # Process Datetime
    if 'datetime' in df.columns:
        df['datetime'] = pd.to_datetime(df['datetime'])
        df = df.sort_values('datetime')
        df['hour'] = df['datetime'].dt.hour
        df['month'] = df['datetime'].dt.month
        
    # Get the last row (most recent data point)
    latest_row = df.iloc[[-1]].copy()
    print(f"Forecasting based on data timestamp: {latest_row['datetime'].values[0]}")
    return latest_row

def main():
    # 1. Load Model System
    if not os.path.exists(MODEL_PATH):
        print(f"Error: Model file not found at {MODEL_PATH}. Please run the Training Notebook first!")
        return

    print(f"Loading model system...")
    bundle = joblib.load(MODEL_PATH)
    
    models = bundle['models']
    scaler = bundle['scaler']
    features = bundle['features']
    horizons = bundle['horizons']

    # 2. Fetch Input Data
    df_new = get_latest_data_from_csv()
    if df_new is None: return

    # Check for missing columns
    missing_cols = set(features) - set(df_new.columns)
    if missing_cols:
        print(f"Error: Input data is missing columns: {missing_cols}")
        # Fill missing with 0 to prevent crash (optional)
        for c in missing_cols: df_new[c] = 0

    # 3. Preprocessing
    X_new = scaler.transform(df_new[features])
    
    # 4. Generate Forecasts
    print("\n=== HO CHI MINH CITY WEATHER FORECAST ===")
    results = []
    
    # Select Best Model based on Validation Results (XGBoost)
    BEST_MODEL = "XGBoost" 

    for h_name in horizons.keys():
        row = {'Horizon': h_name}
        
        # Forecast Temperature
        key_temp = f"{BEST_MODEL}_temp_future_{h_name}"
        if key_temp in models:
            val = models[key_temp].predict(X_new)[0]
            row['Temp (°C)'] = round(val, 1)
            
        # Forecast Precipitation (with non-negative constraint)
        key_precip = f"{BEST_MODEL}_precip_future_{h_name}"
        if key_precip in models:
            val = models[key_precip].predict(X_new)[0]
            row['Precip (mm)'] = max(0.0, round(val, 2))
            
        # Forecast Humidity (constrained 0-100%)
        key_hum = f"{BEST_MODEL}_humidity_future_{h_name}"
        if key_hum in models:
            val = models[key_hum].predict(X_new)[0]
            row['Humidity (%)'] = max(0.0, min(100.0, round(val, 1)))
            
        results.append(row)
        
    # Display Results Table
    print(pd.DataFrame(results).to_string(index=False))

if __name__ == "__main__":
    main()